final tags = [
  'Animals',
  'Business and Brands',
  'Criminal Justice',
  'Environment',
  'Education',
  'Economic justice',
  'Entertainment',
  'Criminals',
  'Food',
  'Health',
  'Human Rights',
  'Politics',
  'Emigration',
  'LGBTQ+',
  'Women\'s rights',
  'Other',
];
